---
services:
  postgres:
    image: postgres:15
    ports:
      - 5432:5432
    volumes:
      - pg-managed-data:/var/lib/postgresql/data
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_DB: example

volumes:
  pg-managed-data:
